import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from app import app
from database import db
from models import Course, Lesson

LESSON_VIDS = ["kqtD5dpn9C8", "DZwmZ8Usvnk", "9Os0o3wzS_I", "JeznW_7DlB0"]
LESSON_TITLES = ["Introduction & Overview", "Core Concepts", "Hands-on Practice", "Advanced Topics", "Project & Review"]

def make_lessons(course_id, main_vid):
    vids = [main_vid] + LESSON_VIDS
    return [Lesson(course_id=course_id, title=LESSON_TITLES[i],
                   video_url=f"https://www.youtube.com/watch?v={vids[i]}",
                   lesson_order=i+1) for i in range(5)]

COURSES = [
  # ── PYTHON ──
  dict(title="Complete Python by Shradha Khapra", instructor="Shradha Khapra",
       thumbnail="https://img.youtube.com/vi/_uQrJ0TkZlc/maxresdefault.jpg",
       duration_weeks=12, rating=4.8, is_premium=False, category="Python", level="Beginner",
       description="Complete Python from scratch covering variables, loops, functions and OOP.", main_vid="_uQrJ0TkZlc"),
  dict(title="Python Programming by Telusko", instructor="Telusko",
       thumbnail="https://img.youtube.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
       duration_weeks=10, rating=4.7, is_premium=False, category="Python", level="Beginner",
       description="Learn Python from basics to advanced with Telusko's popular series.", main_vid="PkZNo7MFNFg"),
  dict(title="Python Course by CODE WITH HURRY", instructor="CODE WITH HURRY",
       thumbnail="https://img.youtube.com/vi/EyEqWkEkFWA/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="Python", level="Beginner",
       description="Python programming with practical examples and real projects.", main_vid="EyEqWkEkFWA"),
  dict(title="Python by Engineering in Kannada", instructor="Engineering in Kannada",
       thumbnail="https://img.youtube.com/vi/UrsmFxEIp5k/maxresdefault.jpg",
       duration_weeks=6, rating=4.6, is_premium=False, category="Python", level="Beginner",
       description="Python programming explained in Kannada for regional learners.", main_vid="UrsmFxEIp5k"),
  dict(title="Python by Jenny's Lectures", instructor="Jenny's Lectures CS IT",
       thumbnail="https://img.youtube.com/vi/6tNm-qgg-2U/maxresdefault.jpg",
       duration_weeks=9, rating=4.7, is_premium=False, category="Python", level="Beginner",
       description="Structured Python lectures covering CS fundamentals and programming.", main_vid="6tNm-qgg-2U"),
  dict(title="Python for Data Science", instructor="Data with Baraa",
       thumbnail="https://img.youtube.com/vi/nLRL_NcnK-4/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="Python", level="Intermediate",
       description="Python for data science including pandas, numpy and visualization.", main_vid="nLRL_NcnK-4"),
  dict(title="Advanced Python by Telusko", instructor="Telusko",
       thumbnail="https://img.youtube.com/vi/p15xzjzR9j0/maxresdefault.jpg",
       duration_weeks=10, rating=4.8, is_premium=True, category="Python", level="Advanced",
       description="Advanced Python: decorators, generators, async, metaclasses.", main_vid="p15xzjzR9j0"),
  dict(title="Python Certification by Simplilearn", instructor="Simplilearn",
       thumbnail="https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg",
       duration_weeks=12, rating=4.6, is_premium=True, category="Python", level="Intermediate",
       description="Certification-ready Python course covering all exam topics.", main_vid="rfscVS0vtbw"),
  dict(title="Python Full Course by freeCodeCamp", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/eWRfhZUzrAc/maxresdefault.jpg",
       duration_weeks=14, rating=4.9, is_premium=False, category="Python", level="Beginner",
       description="Comprehensive Python course from freeCodeCamp covering everything.", main_vid="eWRfhZUzrAc"),
  dict(title="Python OOP by Corey Schafer", instructor="Corey Schafer",
       thumbnail="https://img.youtube.com/vi/ZDa-Z5JzLYM/maxresdefault.jpg",
       duration_weeks=6, rating=4.9, is_premium=False, category="Python", level="Intermediate",
       description="Master object-oriented programming in Python with Corey Schafer.", main_vid="ZDa-Z5JzLYM"),
  # ── WEB DEVELOPMENT ──
  dict(title="Web Development by Apna College", instructor="Apna College",
       thumbnail="https://img.youtube.com/vi/tVzUXW6siu0/maxresdefault.jpg",
       duration_weeks=12, rating=4.8, is_premium=False, category="Web Development", level="Beginner",
       description="Full web development course covering HTML, CSS, JavaScript and more.", main_vid="tVzUXW6siu0"),
  dict(title="Web Dev by CODE WITH HURRY", instructor="CODE WITH HURRY",
       thumbnail="https://img.youtube.com/vi/G3e-cpL7ofc/maxresdefault.jpg",
       duration_weeks=10, rating=4.7, is_premium=False, category="Web Development", level="Beginner",
       description="Web development from scratch with hands-on projects.", main_vid="G3e-cpL7ofc"),
  dict(title="Web Dev by CodeHelp", instructor="CodeHelp by Babbar",
       thumbnail="https://img.youtube.com/vi/HcOc7P5BMi4/maxresdefault.jpg",
       duration_weeks=14, rating=4.8, is_premium=False, category="Web Development", level="Beginner",
       description="Complete web development bootcamp by Love Babbar.", main_vid="HcOc7P5BMi4"),
  dict(title="Web Dev by CODER ARMY", instructor="CODER ARMY",
       thumbnail="https://img.youtube.com/vi/BsDoLVMnmZs/maxresdefault.jpg",
       duration_weeks=8, rating=4.6, is_premium=False, category="Web Development", level="Beginner",
       description="Web development fundamentals with practical coding exercises.", main_vid="BsDoLVMnmZs"),
  dict(title="Full Stack Web Dev by Traversy", instructor="Traversy Media",
       thumbnail="https://img.youtube.com/vi/ysEN5RaKOlA/maxresdefault.jpg",
       duration_weeks=16, rating=4.9, is_premium=True, category="Web Development", level="Intermediate",
       description="Full stack web development covering frontend and backend technologies.", main_vid="ysEN5RaKOlA"),
  dict(title="HTML & CSS Full Course", instructor="SuperSimpleDev",
       thumbnail="https://img.youtube.com/vi/G3e-cpL7ofc/maxresdefault.jpg",
       duration_weeks=6, rating=4.8, is_premium=False, category="Web Development", level="Beginner",
       description="Learn HTML and CSS from scratch with simple, clear explanations.", main_vid="G3e-cpL7ofc"),
  dict(title="CSS Flexbox & Grid", instructor="Kevin Powell",
       thumbnail="https://img.youtube.com/vi/phWxA89Dy94/maxresdefault.jpg",
       duration_weeks=4, rating=4.9, is_premium=False, category="Web Development", level="Intermediate",
       description="Master CSS Flexbox and Grid layout systems with Kevin Powell.", main_vid="phWxA89Dy94"),
  dict(title="Tailwind CSS Full Course", instructor="Dave Gray",
       thumbnail="https://img.youtube.com/vi/lCxcTsOHrjo/maxresdefault.jpg",
       duration_weeks=4, rating=4.8, is_premium=False, category="Web Development", level="Beginner",
       description="Complete Tailwind CSS course covering utility-first CSS framework.", main_vid="lCxcTsOHrjo"),
  dict(title="Bootstrap 5 Full Course", instructor="Academind",
       thumbnail="https://img.youtube.com/vi/4sosXZsdy-s/maxresdefault.jpg",
       duration_weeks=5, rating=4.6, is_premium=False, category="Web Development", level="Beginner",
       description="Bootstrap 5 complete guide for building responsive websites.", main_vid="4sosXZsdy-s"),
  dict(title="Web Dev Bootcamp by Colt Steele", instructor="Colt Steele",
       thumbnail="https://img.youtube.com/vi/1Rs2ND1ryYc/maxresdefault.jpg",
       duration_weeks=20, rating=4.9, is_premium=True, category="Web Development", level="Beginner",
       description="The most comprehensive web development bootcamp covering everything.", main_vid="1Rs2ND1ryYc"),
  # ── JAVASCRIPT ──
  dict(title="JavaScript Full Course by Bro Code", instructor="Bro Code",
       thumbnail="https://img.youtube.com/vi/lfmg-EJ8gm4/maxresdefault.jpg",
       duration_weeks=10, rating=4.7, is_premium=False, category="JavaScript", level="Beginner",
       description="Complete JavaScript course from beginner to advanced concepts.", main_vid="lfmg-EJ8gm4"),
  dict(title="JavaScript by Akshay Saini", instructor="Akshay Saini",
       thumbnail="https://img.youtube.com/vi/pN6jk0uUrD8/maxresdefault.jpg",
       duration_weeks=8, rating=4.9, is_premium=False, category="JavaScript", level="Intermediate",
       description="Namaste JavaScript - deep dive into JS internals and advanced concepts.", main_vid="pN6jk0uUrD8"),
  dict(title="React JS Full Course by Dave Gray", instructor="Dave Gray",
       thumbnail="https://img.youtube.com/vi/RVFAyFWO4go/maxresdefault.jpg",
       duration_weeks=8, rating=4.9, is_premium=True, category="JavaScript", level="Intermediate",
       description="Complete React JS course covering hooks, context, and modern patterns.", main_vid="RVFAyFWO4go"),
  dict(title="Next.js Full Course", instructor="Traversy Media",
       thumbnail="https://img.youtube.com/vi/mTz0GXj8NN0/maxresdefault.jpg",
       duration_weeks=8, rating=4.9, is_premium=True, category="JavaScript", level="Intermediate",
       description="Next.js full course covering SSR, SSG, API routes and deployment.", main_vid="mTz0GXj8NN0"),
  dict(title="Vue.js 3 Full Course", instructor="Net Ninja",
       thumbnail="https://img.youtube.com/vi/YrxBCBibVo0/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="JavaScript", level="Intermediate",
       description="Vue.js 3 complete course with Composition API and Vuex.", main_vid="YrxBCBibVo0"),
  dict(title="TypeScript Full Course", instructor="Academind",
       thumbnail="https://img.youtube.com/vi/BwuLxPH8IDs/maxresdefault.jpg",
       duration_weeks=6, rating=4.8, is_premium=False, category="JavaScript", level="Intermediate",
       description="TypeScript from scratch - types, interfaces, generics and more.", main_vid="BwuLxPH8IDs"),
  dict(title="Node.js & Express by Traversy", instructor="Traversy Media",
       thumbnail="https://img.youtube.com/vi/Oe421EPjeBE/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="JavaScript", level="Intermediate",
       description="Node.js and Express.js crash course for building REST APIs.", main_vid="Oe421EPjeBE"),
  dict(title="JavaScript DOM Manipulation", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/5fb2aPlgoys/maxresdefault.jpg",
       duration_weeks=4, rating=4.7, is_premium=False, category="JavaScript", level="Beginner",
       description="Learn DOM manipulation with vanilla JavaScript through projects.", main_vid="5fb2aPlgoys"),
  # ── DATA SCIENCE ──
  dict(title="Machine Learning by Sentdex", instructor="Sentdex",
       thumbnail="https://img.youtube.com/vi/OGxgnH8y2NM/maxresdefault.jpg",
       duration_weeks=16, rating=4.8, is_premium=True, category="Data Science", level="Intermediate",
       description="Practical machine learning with Python and scikit-learn.", main_vid="OGxgnH8y2NM"),
  dict(title="Deep Learning with TensorFlow", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/tPYj3fFJGjk/maxresdefault.jpg",
       duration_weeks=14, rating=4.8, is_premium=True, category="Data Science", level="Advanced",
       description="Deep learning with TensorFlow and Keras from scratch.", main_vid="tPYj3fFJGjk"),
  dict(title="Data Science Full Course", instructor="Simplilearn",
       thumbnail="https://img.youtube.com/vi/ua-CiDNNj30/maxresdefault.jpg",
       duration_weeks=12, rating=4.6, is_premium=False, category="Data Science", level="Beginner",
       description="Complete data science course covering statistics, Python, and ML.", main_vid="ua-CiDNNj30"),
  dict(title="Pandas & NumPy Tutorial", instructor="Corey Schafer",
       thumbnail="https://img.youtube.com/vi/vmEHCJofslg/maxresdefault.jpg",
       duration_weeks=6, rating=4.8, is_premium=False, category="Data Science", level="Intermediate",
       description="Master Pandas and NumPy for data manipulation and analysis.", main_vid="vmEHCJofslg"),
  dict(title="Power BI Full Course", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/NNSHu0rkew8/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="Data Science", level="Beginner",
       description="Power BI complete course for data visualization and business intelligence.", main_vid="NNSHu0rkew8"),
  dict(title="Statistics for Data Science", instructor="StatQuest",
       thumbnail="https://img.youtube.com/vi/qBigTkBLU6g/maxresdefault.jpg",
       duration_weeks=10, rating=4.9, is_premium=False, category="Data Science", level="Beginner",
       description="Statistics fundamentals for data science explained clearly.", main_vid="qBigTkBLU6g"),
  # ── DEVOPS ──
  dict(title="Docker Tutorial by TechWorld", instructor="TechWorld with Nana",
       thumbnail="https://img.youtube.com/vi/3c-iBn73dDE/maxresdefault.jpg",
       duration_weeks=10, rating=4.8, is_premium=True, category="DevOps", level="Intermediate",
       description="Docker complete tutorial from basics to production deployment.", main_vid="3c-iBn73dDE"),
  dict(title="Kubernetes Crash Course", instructor="TechWorld with Nana",
       thumbnail="https://img.youtube.com/vi/s_o8dwzRlu4/maxresdefault.jpg",
       duration_weeks=8, rating=4.8, is_premium=True, category="DevOps", level="Advanced",
       description="Kubernetes complete course for container orchestration.", main_vid="s_o8dwzRlu4"),
  dict(title="Git & GitHub by Traversy", instructor="Traversy Media",
       thumbnail="https://img.youtube.com/vi/SWYqp7iY_Tc/maxresdefault.jpg",
       duration_weeks=4, rating=4.9, is_premium=False, category="DevOps", level="Beginner",
       description="Git and GitHub crash course for version control and collaboration.", main_vid="SWYqp7iY_Tc"),
  dict(title="Linux Command Line", instructor="NetworkChuck",
       thumbnail="https://img.youtube.com/vi/ZtqBQ68cfJc/maxresdefault.jpg",
       duration_weeks=4, rating=4.8, is_premium=False, category="DevOps", level="Beginner",
       description="Linux command line fundamentals for developers and sysadmins.", main_vid="ZtqBQ68cfJc"),
  dict(title="AWS Cloud Practitioner", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/SOTamWNgDKc/maxresdefault.jpg",
       duration_weeks=12, rating=4.7, is_premium=True, category="DevOps", level="Intermediate",
       description="AWS Cloud Practitioner certification prep course.", main_vid="SOTamWNgDKc"),
  # ── DATABASE ──
  dict(title="SQL Full Course by freeCodeCamp", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/HXV3zeQKqGY/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="Database", level="Beginner",
       description="Complete SQL course covering queries, joins, and database design.", main_vid="HXV3zeQKqGY"),
  dict(title="MySQL Full Course", instructor="Bro Code",
       thumbnail="https://img.youtube.com/vi/5OdVJbNCSso/maxresdefault.jpg",
       duration_weeks=6, rating=4.7, is_premium=False, category="Database", level="Beginner",
       description="MySQL complete course from installation to advanced queries.", main_vid="5OdVJbNCSso"),
  dict(title="MongoDB Full Course", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/ExcRbA7fy_A/maxresdefault.jpg",
       duration_weeks=6, rating=4.6, is_premium=False, category="Database", level="Beginner",
       description="MongoDB NoSQL database complete course with Node.js integration.", main_vid="ExcRbA7fy_A"),
  dict(title="PostgreSQL Full Course", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/qw--VYLpxG4/maxresdefault.jpg",
       duration_weeks=8, rating=4.7, is_premium=False, category="Database", level="Intermediate",
       description="PostgreSQL complete course covering advanced SQL and administration.", main_vid="qw--VYLpxG4"),
  dict(title="GraphQL Full Course", instructor="Traversy Media",
       thumbnail="https://img.youtube.com/vi/ed8SzALpx1Q/maxresdefault.jpg",
       duration_weeks=6, rating=4.7, is_premium=True, category="Database", level="Intermediate",
       description="GraphQL complete course for building flexible APIs.", main_vid="ed8SzALpx1Q"),
  # ── DSA ──
  dict(title="DSA by freeCodeCamp", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/pkYVOmU3MgA/maxresdefault.jpg",
       duration_weeks=14, rating=4.9, is_premium=False, category="DSA", level="Intermediate",
       description="Data structures and algorithms complete course with Python.", main_vid="pkYVOmU3MgA"),
  dict(title="DSA by Abdul Bari", instructor="Abdul Bari",
       thumbnail="https://img.youtube.com/vi/0IAPZzGSbME/maxresdefault.jpg",
       duration_weeks=16, rating=4.9, is_premium=False, category="DSA", level="Intermediate",
       description="Data structures and algorithms with detailed visual explanations.", main_vid="0IAPZzGSbME"),
  dict(title="Competitive Programming", instructor="Errichto",
       thumbnail="https://img.youtube.com/vi/xAeiXy8-9Y8/maxresdefault.jpg",
       duration_weeks=12, rating=4.8, is_premium=True, category="DSA", level="Advanced",
       description="Competitive programming techniques and problem-solving strategies.", main_vid="xAeiXy8-9Y8"),
  dict(title="LeetCode Patterns by NeetCode", instructor="NeetCode",
       thumbnail="https://img.youtube.com/vi/KLlXCFG5TnA/maxresdefault.jpg",
       duration_weeks=10, rating=4.9, is_premium=True, category="DSA", level="Advanced",
       description="Master LeetCode patterns and ace coding interviews with NeetCode.", main_vid="KLlXCFG5TnA"),
  # ── JAVA ──
  dict(title="Java Full Course by Amigoscode", instructor="Amigoscode",
       thumbnail="https://img.youtube.com/vi/Qgl81fPcLc8/maxresdefault.jpg",
       duration_weeks=12, rating=4.7, is_premium=False, category="Java", level="Beginner",
       description="Java complete course from basics to object-oriented programming.", main_vid="Qgl81fPcLc8"),
  dict(title="Spring Boot Full Course", instructor="Amigoscode",
       thumbnail="https://img.youtube.com/vi/9SGDpanrc8U/maxresdefault.jpg",
       duration_weeks=10, rating=4.8, is_premium=True, category="Java", level="Intermediate",
       description="Spring Boot complete course for building production-ready Java apps.", main_vid="9SGDpanrc8U"),
  dict(title="Java DSA by Kunal Kushwaha", instructor="Kunal Kushwaha",
       thumbnail="https://img.youtube.com/vi/rZ41y93P2Qo/maxresdefault.jpg",
       duration_weeks=16, rating=4.9, is_premium=False, category="Java", level="Beginner",
       description="Data structures and algorithms in Java with Kunal Kushwaha.", main_vid="rZ41y93P2Qo"),
  dict(title="Android Development Java", instructor="freeCodeCamp",
       thumbnail="https://img.youtube.com/vi/fis26HvvDII/maxresdefault.jpg",
       duration_weeks=14, rating=4.6, is_premium=False, category="Java", level="Intermediate",
       description="Android app development with Java from scratch.", main_vid="fis26HvvDII"),
  # ── MOBILE / OTHER ──
  dict(title="Flutter & Dart Full Course", instructor="Net Ninja",
       thumbnail="https://img.youtube.com/vi/1ukSR1GRtMU/maxresdefault.jpg",
       duration_weeks=12, rating=4.8, is_premium=True, category="Mobile", level="Intermediate",
       description="Flutter and Dart complete course for cross-platform mobile development.", main_vid="1ukSR1GRtMU"),
  dict(title="Rust Programming Language", instructor="Let's Get Rusty",
       thumbnail="https://img.youtube.com/vi/ygL_xcavzQ4/maxresdefault.jpg",
       duration_weeks=10, rating=4.7, is_premium=True, category="Other", level="Advanced",
       description="Rust programming language complete course covering ownership and safety.", main_vid="ygL_xcavzQ4"),
  dict(title="C++ Full Course by Bro Code", instructor="Bro Code",
       thumbnail="https://img.youtube.com/vi/-TkoO8Z07hI/maxresdefault.jpg",
       duration_weeks=10, rating=4.6, is_premium=False, category="Other", level="Beginner",
       description="C++ complete course from basics to object-oriented programming.", main_vid="-TkoO8Z07hI"),
]


def seed():
    with app.app_context():
        print("Clearing existing data...")
        Lesson.query.delete()
        Course.query.delete()
        db.session.commit()
        print("Seeding 55 courses...")
        for data in COURSES:
            main_vid = data.pop("main_vid")
            course = Course(**{k: v for k, v in data.items()})
            db.session.add(course)
            db.session.flush()
            for lesson in make_lessons(course.id, main_vid):
                db.session.add(lesson)
        db.session.commit()
        print(f"Done! Seeded {Course.query.count()} courses with {Lesson.query.count()} lessons.")


if __name__ == "__main__":
    seed()
